#spring.datasource.url=jdbc:h2:./devdb
#spring.jpa.hibernate.ddl-auto=update
spring:  
 jpa:   
  properties:   
    javax:
        persistence:
          validation:
            mode: none
            data: 
               web:      
               pageable:       
                default-page-size: 10
        max-page-size: 100 
 profiles:
   active:
   - dev
 servlet:
    multipart:
      max-file-size: 10MB

---
spring:
  profiles: production
tweet:
  upload-path: storage-production
---
spring:
  profiles: dev
 
  jpa:
    hibernate:
      ddl-auto: update
tweet:
  upload-path: storage-dev

